swagger: "2.0"
info:
  version: "1.0.0"
  title: Historical Event
  description: Histroical Event System
host: 'localhost:3000'
basePath: /
tags: 
- name: Historical Event
  description: Historical Event Management
schemes: 
- http
- https
consumes:
  - application/json
produces:
  - application/json
paths:
  /events/getEventByEmail/{email}:
    get:
      tags:
      - Get Event by email
      summary: Get Event by email
      description: Event by Email
      parameters: 
      - name: email
        in: path
        description: Email 
        required: true
        type: string
      responses:
        '200':
          description: OK
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /events/getAllEvents:
    get:
      tags:
      - get All Events
      summary: get All Events
      description: To get All Events
      responses:
        '200':
          description: Event Data
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    x-swagger-router-controller: eventController
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Event:
    type: object
    properties:
      email:
        type: string
      environment:
        type: string
      component:
        type: string
      message:
        type: string
      data:
        type: object
        items:
          $ref: '#/definitions/EventData'
  EventData:
    type: object
    properties:
      order_id:
        type: string
      amount:
        type: string